server:
  port: 5000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: krm@root
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect